
#execution:
#  multiprocess:
#    config:
#      max_concurrent: 2
#storage:
#  filesystem:
#    config:
#      base_dir: ''

solids:

  solid_generator_4gkb:
    inputs:
      path_bad_data: 'bad/urls.delta'
      path_target: 'raw/url/4gkb.delta'
    config:
      default_start_state: '1'
      max_n_fails: 35

  solid_generator_komzdrav:
    inputs:
      path_bad_data: 'bad/urls.delta'
      path_target: 'raw/url/komzdrav.delta'
    config:
      default_start_state: '1'
      max_n_fails: 5

  solid_generator_naviny:
    inputs:
      path_bad_data: 'bad/urls.delta'
      path_target: 'raw/url/naviny.delta'
    config:
      default_start_state: '2021/02/20'

  solid_generator_tutby:
    inputs:
      path_bad_data: 'bad/urls.delta'
      path_target: 'raw/url/tutby.delta'
    config:
      default_start_state: '720500'
      max_n_fails: 10

  solid_scraper_4gkb:
    inputs:
      path_target: 'raw/html/4gkb.delta'

  solid_scraper_komzdrav:
    inputs:
      path_target: 'raw/html/komzdrav.delta'

  solid_scraper_naviny:
    inputs:
      path_target: 'raw/html/naviny.delta'

  solid_scraper_tutby:
    inputs:
      path_target: 'raw/html/tutby.delta'

  solid_structured_4gkb:
    inputs:
      path_target: 'structured/4gkb.delta'

  solid_structured_komzdrav:
    inputs:
      path_target: 'structured/komzdrav.delta'

  solid_structured_naviny:
    inputs:
      path_target: 'structured/naviny.delta'

  solid_structured_tutby:
    inputs:
      path_target: 'structured/tutby.delta'
