
#execution:
#  multiprocess:
#    config:
#      max_concurrent: 2
#storage:
#  filesystem:
#    config:
#      base_dir: ''

solids:

  solid_generator_4gkb:
    inputs:
      path_bad_data: 'bad/urls.delta'
      path_target: 'raw/url/4gkb.delta'
    config:
      default_start_state: '1'
      max_n_fails: 35

  solid_generator_komzdrav:
    inputs:
      path_bad_data: 'bad/urls.delta'
      path_target: 'raw/url/komzdrav.delta'
    config:
      default_start_state: '1'
      max_n_fails: 5

  solid_generator_naviny:
    inputs:
      path_bad_data: 'bad/urls.delta'
      path_target: 'raw/url/naviny.delta'
    config:
      default_start_state: '2021/03/01'

  solid_generator_tutby:
    inputs:
      path_bad_data: 'bad/urls.delta'
      path_target: 'raw/url/tutby.delta'
    config:
      default_start_state: '721400'
      max_n_fails: 10

  solid_scraper_4gkb:
    inputs:
      path_target: 'raw/html/4gkb.delta'

  solid_scraper_komzdrav:
    inputs:
      path_target: 'raw/html/komzdrav.delta'

  solid_scraper_naviny:
    inputs:
      path_target: 'raw/html/naviny.delta'

  solid_scraper_tutby:
    inputs:
      path_target: 'raw/html/tutby.delta'

  solid_structured_4gkb:
    inputs:
      path_target: 'structured/4gkb.delta'

  solid_structured_komzdrav:
    inputs:
      path_target: 'structured/komzdrav.delta'

  solid_structured_naviny:
    inputs:
      path_target: 'structured/naviny.delta'

  solid_structured_tutby:
    inputs:
      path_target: 'structured/tutby.delta'

  solid_curated_4gkb:
    config:
      process_name: 'curated_4gkb'
    inputs:
      path_target: 'curated/article.delta'

  solid_curated_komzdrav:
    config:
      process_name: 'curated_komzdrav'
    inputs:
      path_target: 'curated/article.delta'

  solid_curated_naviny:
    config:
      process_name: 'curated_naviny'
    inputs:
      path_target: 'curated/article.delta'

  solid_curated_tutby:
    config:
      process_name: 'curated_tutby'
    inputs:
      path_target: 'curated/article.delta'

  solid_preprocessing:
    config:
      process_name: 'preprocessing'
    inputs:
      path_target: 'analytics/preprocessed.delta'
