name: pyspark_conda_env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - conda-pack
  - psycopg2
  - pandas
  - pyarrow
  - requests
  - beautifulsoup4
  - nltk
  - pip
  - pip:
    - pymystem3
